# Generated by Django 4.2.25 on 2025-11-04 01:32
from __future__ import annotations

import hashlib
import json
import logging

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

logger = logging.getLogger("core.moderation")


def populate_archivefile_signatures(apps, schema_editor):
    ArchiveFile = apps.get_model("core", "ArchiveFile")
    try:
        from core.utils import moderation
    except Exception:  # pragma: no cover - fallback for historical migrations
        moderation = None

    def normalise(value: str) -> str:
        if moderation:
            return moderation.normalise_text(value)
        return (value or "").strip().lower()

    def compute_hash(title, data) -> str:
        if moderation:
            return moderation.compute_content_hash(title, data)
        try:
            serialised = json.dumps(data, ensure_ascii=False, sort_keys=True) if isinstance(data, (dict, list)) else str(data)
        except Exception:
            serialised = str(data)
        payload = f"{normalise(title)}\n{serialised}".strip()
        return hashlib.sha256(payload.encode("utf-8")).hexdigest() if payload else ""

    seen_titles: dict[tuple[int, str], int] = {}
    seen_hashes: dict[tuple[int, str], int] = {}

    for archive in ArchiveFile.objects.select_related("rubric__profile__user"):
        rubric = archive.rubric
        owner = None
        if rubric and rubric.profile_id:
            owner = rubric.profile.user
        if owner is None:
            logger.warning("Archive file %s has no owner profile; skipping", archive.pk)
            continue

        normalized_title = normalise(archive.title)
        content_hash = compute_hash(archive.title, archive.data)

        title_key = (owner.pk, normalized_title)
        if title_key in seen_titles:
            logger.warning(
                "Duplicate archive title detected for owner %s between %s and %s",
                owner.pk,
                seen_titles[title_key],
                archive.pk,
            )
            suffix = f"__legacy_{archive.pk}"
            normalized_title = f"{normalized_title[: max(0, 255 - len(suffix))]}{suffix}"
        else:
            seen_titles[title_key] = archive.pk

        hash_key = (owner.pk, content_hash)
        if content_hash and hash_key in seen_hashes:
            logger.warning(
                "Duplicate archive content detected for owner %s between %s and %s",
                owner.pk,
                seen_hashes[hash_key],
                archive.pk,
            )
            suffix = f"-legacy-{archive.pk}"
            allowed = max(0, 64 - len(suffix))
            content_hash = f"{content_hash[:allowed]}{suffix}"
        elif content_hash:
            seen_hashes[hash_key] = archive.pk

        archive.owner = owner
        archive.normalized_title = normalized_title
        archive.content_hash = content_hash
        archive.save(update_fields=["owner", "normalized_title", "content_hash"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivefile",
            name="content_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="archivefile",
            name="normalized_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="archivefile",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="terms_accepted_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="terms_version_accepted",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.RunPython(populate_archivefile_signatures, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="archivefile",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="archivefile",
            constraint=models.UniqueConstraint(
                fields=("owner", "normalized_title"), name="uniq_archive_owner_title"
            ),
        ),
        migrations.AddConstraint(
            model_name="archivefile",
            constraint=models.UniqueConstraint(
                fields=("owner", "content_hash"), name="uniq_archive_owner_hash"
            ),
        ),
    ]
