# Generated by Django 4.2.30 on 2026-09-11 04:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ensure_license_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=120)),
                ('question', models.TextField(max_length=10000)),
                ('source', models.CharField(default='website', editable=False, max_length=16)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('work', 'В работе'), ('answered', 'Отвечено')], db_index=True, default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sender_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SupportReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=20000)),
                ('sent_at', models.DateTimeField()),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.supportticket')),
            ],
        ),
    ]
