# Generated by Django 4.2.25 on 2025-11-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_archivefile_content_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="link",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
