# Generated by Django 4.2.26 on 2025-11-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profile_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=255, unique=True)),
                ("passwor", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("mail", models.EmailField(max_length=255)),
                ("link", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=255)),
                ("interests", models.TextField()),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("delete", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["login"],
            },
        ),
    ]
