# Generated by Django 4.2.30 on 2026-06-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_directmessage_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
