# Generated by Django 4.2.30 on 2026-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rubric_is_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivefile',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
