# Generated by Codex on 2026-06-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


DEFAULT_PLANS = {
    'free': {
        'name': 'Free',
        'description': 'Basic account features.',
        'archive_limit': 100,
        'active_auction_limit': 3,
        'is_paid': False,
        'sort_order': 10,
    },
    'plus': {
        'name': 'Plus',
        'description': 'Expanded archive and auction limits.',
        'archive_limit': 20000,
        'active_auction_limit': 20,
        'monthly_price': '99.00',
        'yearly_price': '990.00',
        'is_paid': True,
        'sort_order': 20,
    },
    'pro': {
        'name': 'Pro',
        'description': 'Professional archive and auction limits.',
        'archive_limit': 20000,
        'active_auction_limit': 100,
        'monthly_price': '199.00',
        'yearly_price': '1990.00',
        'is_paid': True,
        'sort_order': 30,
    },
}


def seed_plans_and_free_subscriptions(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    SubscriptionPlan = apps.get_model('core', 'SubscriptionPlan')
    UserSubscription = apps.get_model('core', 'UserSubscription')
    SubscriptionHistory = apps.get_model('core', 'SubscriptionHistory')
    now = django.utils.timezone.now()

    plans = {}
    for code, defaults in DEFAULT_PLANS.items():
        plan, _ = SubscriptionPlan.objects.update_or_create(code=code, defaults=defaults)
        plans[code] = plan

    free_plan = plans['free']
    for user in User.objects.all().iterator():
        if UserSubscription.objects.filter(user=user, status='active').exists():
            continue
        subscription = UserSubscription.objects.create(
            user=user,
            plan=free_plan,
            starts_at=now,
            ends_at=None,
            status='active',
            billing_period='free',
            auto_renew=False,
        )
        SubscriptionHistory.objects.create(
            user=user,
            subscription=subscription,
            to_plan=free_plan,
            to_status='active',
            billing_period='free',
            reason='free_assigned_migration',
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_directmessage_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('archive_limit', models.PositiveIntegerField()),
                ('active_auction_limit', models.PositiveIntegerField()),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('billing_period', models.CharField(choices=[('free', 'Free'), ('month', 'Month'), ('year', 'Year')], default='free', max_length=16)),
                ('auto_renew', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=16)),
                ('to_status', models.CharField(blank=True, default='', max_length=16)),
                ('billing_period', models.CharField(blank=True, default='', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('from_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.subscriptionplan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='core.usersubscription')),
                ('to_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='usersub_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'ends_at'], name='usersub_status_end_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionhistory',
            index=models.Index(fields=['user', 'changed_at'], name='subhist_user_changed_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='uniq_active_subscription_per_user'),
        ),
        migrations.RunPython(seed_plans_and_free_subscriptions, migrations.RunPython.noop),
    ]
