# Generated by Codex on 2026-06-19

from django.db import migrations, models


PLAN_UPDATES = {
    'plus': {
        'archive_limit': 20000,
        'active_auction_limit': 20,
        'monthly_price': '99.00',
        'yearly_price': '990.00',
        'is_paid': True,
        'is_active': True,
        'sort_order': 20,
    },
    'pro': {
        'archive_limit': None,
        'active_auction_limit': 100,
        'monthly_price': '199.00',
        'yearly_price': '1990.00',
        'is_paid': True,
        'is_active': True,
        'sort_order': 30,
    },
}


def update_paid_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('core', 'SubscriptionPlan')
    for code, values in PLAN_UPDATES.items():
        defaults = {
            'name': code.title(),
            'description': 'Expanded archive and auction limits.' if code == 'plus' else 'Professional archive and auction limits.',
            **values,
        }
        SubscriptionPlan.objects.update_or_create(code=code, defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='archive_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(update_paid_plans, migrations.RunPython.noop),
    ]
