# Generated by Codex on 2026-06-21

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def normalize_subscription_rows(apps, schema_editor):
    UserSubscription = apps.get_model('core', 'UserSubscription')
    UserSubscription.objects.filter(status='cancelled').update(status='canceled')
    for subscription in UserSubscription.objects.select_related('tariff').filter(
        status='active',
        tariff__is_paid=True,
        last_successful_payment__isnull=True,
    ).iterator():
        subscription.last_successful_payment = subscription.starts_at
        subscription.save(update_fields=['last_successful_payment'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_update_subscription_plan_limits_prices'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usersubscription',
            name='usersub_status_end_idx',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='plan',
            new_name='tariff',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='ends_at',
            new_name='expires_at',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='last_successful_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'expires_at'], name='usersub_status_exp_idx'),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('period', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled'), ('failed', 'Failed')], db_index=True, default='created', max_length=16)),
                ('yookassa_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('idempotence_key', models.CharField(max_length=128, unique=True)),
                ('confirmation_url', models.URLField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_activated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(fields=['user', 'status'], name='subpay_user_status_idx'),
                ],
            },
        ),
        migrations.RunPython(normalize_subscription_rows, migrations.RunPython.noop),
    ]
