# Generated by Codex on 2026-06-21

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models
from django.utils import timezone


def create_hidden_test_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('core', 'Profile')

    user, _ = User.objects.get_or_create(
        username='TestUser',
        defaults={
            'email': '',
            'is_active': True,
        },
    )
    user.password = make_password('Pass1234')
    user.is_active = True
    user.save(update_fields=['password', 'is_active'])

    profile, _ = Profile.objects.get_or_create(user=user)
    profile.display_name = ''
    profile.privacy_level = 'private'
    profile.is_hidden = True
    profile.terms_version_accepted = getattr(settings, 'TERMS_VERSION', '')
    profile.terms_accepted_at = profile.terms_accepted_at or timezone.now()
    profile.save(update_fields=[
        'display_name',
        'privacy_level',
        'is_hidden',
        'terms_version_accepted',
        'terms_accepted_at',
    ])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_subscription_payment_and_tariff_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_hidden_test_user, migrations.RunPython.noop),
    ]
