# Generated by Codex on 2026-06-21

from django.db import migrations, models


def blank_payment_ids_to_null(apps, schema_editor):
    SubscriptionPayment = apps.get_model('core', 'SubscriptionPayment')
    SubscriptionPayment.objects.filter(yookassa_payment_id='').update(yookassa_payment_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_hidden_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RunPython(blank_payment_ids_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
