# Generated by Django 4.2.30 on 2026-06-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_listing_auction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auction_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='auction_start_mode',
            field=models.CharField(choices=[('now', 'Начать сразу'), ('scheduled', 'Запланировать')], default='now', max_length=16),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('collecting', 'Коллекционирование'), ('auto', 'Авто'), ('realty', 'Недвижимость'), ('jobs', 'Работа'), ('electronics', 'Электроника'), ('home', 'Для дома и дачи'), ('fashion', 'Одежда, обувь, аксессуары'), ('hobby', 'Хобби и отдых'), ('services', 'Услуги')], db_index=True, max_length=32),
        ),
    ]
