# Generated by Django 4.2.30 on 2026-06-15 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0004_listing_auction_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_winning', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to='market.listing')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['listing'], name='auctionbid_listing_idx'), models.Index(fields=['bidder'], name='auctionbid_bidder_idx'), models.Index(fields=['created_at'], name='auctionbid_created_idx')],
            },
        ),
    ]
