# Generated by Django 4.2.30 on 2026-07-08 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0006_listing_auction_result_listing_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_invalidated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_unpublished',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='moderation_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
