# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_listing_is_invalidated_listing_is_unpublished_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="auction_buy_now_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
