# Generated by Django 4.2.30 on 2026-06-15 14:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0002_listing_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Торги запланированы'), ('active', 'Участвует в торгах'), ('sold', 'Продано'), ('ended', 'Торги завершены'), ('cancelled', 'Отменено')], db_index=True, default='draft', max_length=20)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_bid_step', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('auto_extend', models.BooleanField(default=False)),
                ('extend_seconds', models.PositiveIntegerField(default=0)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('snapshot_images', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction_lot', to='market.listing')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auction_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'end_at'], name='auction_status_end_idx')],
            },
        ),
    ]
