"""Replaces the Java controller route mappings with Django URL patterns."""
from django.urls import path
from django.views.generic import RedirectView

from . import studio, views

app_name = 'core'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('archive/', views.archive, name='archive'),
    path('u/<str:username>/<str:rubric_slug>/', views.public_collection, name='public-collection'),
    path('profile/', views.profile, name='profile'),
    path('community/', views.community, name='community'),
    path('community/users/<str:username>/', views.community_user_profile, name='community-user-profile'),
    path('messages/', views.messages_page, name='messages'),
    path('messages/<int:user_id>/', views.message_dialog_page, name='message-dialog'),
    path('settings/', views.settings, name='settings'),
    path('subscriptions/payment/result/', views.subscription_payment_result, name='payment-result'),
    path('subscriptions/yookassa/webhook/', views.yookassa_webhook, name='yookassa-webhook'),
    path('terms/', views.terms, name='terms'),
    path('requisites/', views.requisites, name='requisites'),
    path('news/', views.news, name='news'),
    path('reviews/', views.reviews, name='reviews'),
    path('index.html', RedirectView.as_view(url='/', permanent=True), name='landing-index-redirect'),
    path('archive.html', RedirectView.as_view(url='/archive/', permanent=True), name='archive-redirect'),
    path('profile.html', RedirectView.as_view(url='/profile/', permanent=True), name='profile-redirect'),
    path('messages.html', RedirectView.as_view(url='/messages/', permanent=True), name='messages-redirect'),
    path('settings.html', RedirectView.as_view(url='/settings/', permanent=True), name='settings-redirect'),
    path('requisites.html', RedirectView.as_view(url='/requisites/', permanent=True), name='requisites-redirect'),
    path('news.html', RedirectView.as_view(url='/news/', permanent=True), name='news-redirect'),
    path('reviews.html', RedirectView.as_view(url='/reviews/', permanent=True), name='reviews-redirect'),
    path('api/auth/register/', views.register_user, name='register'),
    path('api/auth/login/', views.login_user, name='login'),
    path('api/auth/logout/', views.logout_user, name='logout'),
    path('api/subscription/checkout/', views.subscription_checkout, name='subscription-checkout'),

    path('api/auth/status/', views.auth_status, name='auth-status'),
    path('api/auth/check-availability/', views.check_auth_availability, name='auth-check-availability'),
    path('api/profile/', views.profile_api, name='profile-api'),
    path('api/community/summary/', views.community_summary_api, name='community-summary-api'),
    path('api/community/unread-requests/', views.community_unread_requests_api, name='community-unread-requests-api'),
    path('api/community/search/', views.community_search_api, name='community-search-api'),
    path('api/community/friends/', views.community_friends_api, name='community-friends-api'),
    path('api/community/requests/', views.community_requests_api, name='community-requests-api'),
    path('api/community/friendship/', views.community_friendship_action_api, name='community-friendship-api'),
    path('api/messages/dialogs/', views.message_dialogs_api, name='message-dialogs-api'),
    path('api/messages/unread/', views.message_unread_api, name='message-unread-api'),
    path('api/messages/users/<int:user_id>/', views.message_history_api, name='message-history-api'),
    path('api/messages/users/<int:user_id>/read/', views.message_mark_read_api, name='message-mark-read-api'),
    path('api/messages/send/', views.message_send_api, name='message-send-api'),
    path('api/messages/<int:message_id>/edit/', views.message_edit_api, name='message-edit-api'),
    path('api/messages/<int:message_id>/delete/', views.message_delete_api, name='message-delete-api'),
    path('api/messages/<int:message_id>/reaction/', views.message_reaction_api, name='message-reaction-api'),
    path('api/archive/state/', views.archive_state_api, name='archive-state-api'),
    path('api/archive/rubrics/list/', views.list_rubrics, name='rubrics-list'),
    path('api/archive/rubrics/<int:rubric_id>/files/', views.list_rubric_files, name='rubric-files-list'),
    path('api/archive/rubrics/<str:rubric_id>/export/<str:export_format>/', views.export_rubric, name='export-rubric'),
    path('api/archive/files/<int:file_id>/', views.update_archive_file, name='update-file'),
    path('api/archive/files/move/', views.move_archive_file, name='move-file'),
    path('api/archive/files/bulk-delete/', views.bulk_delete_archive_files, name='bulk-delete-files'),
    path('api/archive/files/bulk-move/', views.bulk_move_archive_files, name='bulk-move-files'),
    path('api/reviews/', views.reviews_api, name='reviews-api'),
    path('api/reviews/create/', views.reviews_create_api, name='reviews-create-api'),
    path('api/reviews/<int:review_id>/', views.reviews_update_api, name='reviews-update-api'),
    path('api/archive/rubrics/', views.create_rubric, name='create-rubric'),
    path('api/archive/files/', views.create_archive_file, name='create-file'),
    path('api/terms/accept/', views.accept_terms, name='accept_terms'),

    # --- Hidden site editor / administrator page (superuser only) -----------
    path('studio/', studio.studio_page, name='studio'),
    path('api/studio/login/', studio.studio_login, name='studio-login'),
    path('api/studio/logout/', studio.studio_logout, name='studio-logout'),
    path('api/studio/status/', studio.studio_status, name='studio-status'),
    path('api/studio/diagnostics/', studio.studio_diagnostics, name='studio-diagnostics'),
    path('api/studio/payments/lookup/', studio.studio_payment_lookup, name='studio-payment-lookup'),
    path('api/studio/payments/sync/', studio.studio_payment_sync, name='studio-payment-sync'),
    path('api/studio/news/', studio.studio_news_list, name='studio-news-list'),
    path('api/studio/news/save/', studio.studio_news_save, name='studio-news-save'),
    path('api/studio/news/<int:article_id>/publish/', studio.studio_news_publish, name='studio-news-publish'),
    path('api/studio/news/<int:article_id>/delete/', studio.studio_news_delete, name='studio-news-delete'),
    path('api/studio/users/', studio.studio_users_search, name='studio-users'),
    path('api/studio/users/<int:user_id>/block/', studio.studio_user_block, name='studio-user-block'),
    path('api/studio/users/<int:user_id>/unblock/', studio.studio_user_unblock, name='studio-user-unblock'),
    path('api/studio/listings/', studio.studio_listings, name='studio-listings'),
    path('api/studio/listings/<int:listing_id>/action/', studio.studio_listing_action, name='studio-listing-action'),
    path('api/studio/reviews/', studio.studio_reviews, name='studio-reviews'),
    path('api/studio/reviews/<int:review_id>/action/', studio.studio_review_action, name='studio-review-action'),
]
